model:
  name: yolov11_l
  confidence_threshold: 0.5
  nms_threshold: 0.4

camera:
  width: 1280
  height: 720
  fps: 30

gui:
  window_title: "Real-time Object Detection"
  window_size: "1200x800"
  theme: "dark"